all:
	gcc -c function1.c -o function1.o
	gcc -c function2.c -o function2.o
	gcc -c function3.c -o function3.o
	gcc -c function4.c -o function4.o
	gcc -c function5.c -o function5.o
	
	gcc hw0401.c function1.o -o hw0401
	gcc hw0402-1.c function2.o -o hw0402-1
	gcc hw0403.c function3.o -o hw0403
	gcc hw0404.c function4.o -o hw0404
	gcc hw0405.c function5.o -o hw0405
	
clean:
	rm -f function1.o
	rm -f function2.o
	rm -f function3.o
	rm -f function4.o
	rm -f function5.o
	rm -f hw0401
	rm -f hw0402-1
	rm -f hw0403
	rm -f hw0404
	rm -f hw0405
