all:
	gcc -c mystring.c            -o mystring
	gcc -c myvec.c               -o myvec
	gcc -c basic.c               -o basic
	gcc    mid01.c mystring      -o mid01
	gcc    mid02.c               -o mid02
	gcc    mid03.c myvec basic   -o mid03 -lm