all:
	gcc hw0101.c -o hw0101 -lm
	gcc hw0102.c -o hw0102
	gcc -c mystring.c -o mystring
	gcc hw0103.c mystring -o hw0103
	gcc hw0104.c mystring -o hw0104
	gcc -c mysplit.c -o mysplit
	gcc hw0105.c mysplit -o hw0105