all:
	gcc -c mymatch.c  -o mymatch
	gcc -c mix.c      -o mix
	gcc -c myvector.c -o myvector -lm
	gcc hw0201.c mymatch -o hw0201
	gcc hw0202.c -o hw0202
	gcc hw0204.c mix -o hw0204
	gcc hw0205.c  myvector -o hw0205